version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/data.ms
    environment:
      - MEILI_MASTER_KEY=mySecureMasterKey123456789ABC
    networks:
      - backend

  auth.service:
    container_name: auth.service
    build:
      context: .
      dockerfile: Auth.Service/Dockerfile
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - backend

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - catalog_data:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - redis
    networks:
      - backend

  media.service:
    container_name: media.service
    build:
      context: .
      dockerfile: Media.Service/Dockerfile
    ports:
      - "8001:8080"
    volumes:
      - media_uploads:/app/uploads
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend

  search.service:
    container_name: search.service
    build:
      context: .
      dockerfile: Search.Service/Dockerfile
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - meilisearch
      - redis
    networks:
      - backend

  gateway.yarp:
    container_name: gateway.yarp
    build:
      context: .
      dockerfile: GatewayYarp/Dockerfile
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - catalog.api
      - media.service
      - search.service
      - auth.service
    networks:
      - backend

volumes:
  media_uploads:
  meili_data:
  catalog_data:

networks:
  backend:
    driver: bridge